"use client";
import { useEffect } from "react";
import { readLocal } from "@/lib/storage";
import { PassportMap } from "./PassportMap";
import { Brand, Rules, ORDER_URL } from "./Passport";
export function Landing() {
  useEffect(() => { const token = readLocal("edelweiss_passport_token"); if (token && /^[\w-]{43}$/.test(token)) window.location.replace(`/p/${token}`); }, []);
  return <main className="passport-shell"><Brand/><section className="landing-heading"><p className="eyebrow">Introducing the Edelweiss Swiss Passport</p><h1>A taste of Switzerland.<br/><em>A journey worth savouring.</em></h1><p>From Zürich to the Matterhorn, collect a little piece of Switzerland with every online order.</p><a className="button" href={ORDER_URL}>Start with something delicious <span aria-hidden="true">↗</span></a><span className="landing-note">Your passport arrives in your order email.</span></section><PassportMap/><section className="how-it-works"><p className="eyebrow">A delicious way to get there</p><h2>How it works</h2><div className="steps">{[["01", "Order a little joy", "Place an online order. We’ll send your personal passport in your thank-you email."], ["02", "Collect Swiss memories", "Earn 1 stamp per order, or 2 when your subtotal is over $40. Discover a new Swiss stop each time."], ["03", "Reach the Matterhorn", "Collect 10 stamps and enjoy 15% off your next online order. Your unique code is valid for 30 days."]].map(([n, title, body]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section><Rules/><p className="history-note">No minimum order. Online orders only. Double stamps apply to the subtotal before tax, strictly over $40. One passport and one reward per customer; no rollover. Your code can be used once.</p><div className="landing-cta"><h2>Where will your next treat take you?</h2><a className="button" href={ORDER_URL}>Order online ↗</a></div><footer>Swiss roots. Maine heart. <span aria-hidden="true">✿</span> Edelweiss Pastry Shop</footer></main>;
}
